version: 2

jobs:
  build:
    working_directory: ~/jsonschema2pojo-rules-bettermaps
    docker:
      - image: maven:3.3.9
    steps:
      - checkout
      - restore_cache:
          key: jsonschema2pojo-rules-bettermaps-{{.Branch}}
      - run: mvn package
      - save_cache:
          key: jsonschema2pojo-rules-bettermaps-{{.Branch}}
          paths:
            - "~/.m2/repository"
      - run:
          name: store test results
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/junit/
            cp target/surefire-reports/*.xml $CIRCLE_TEST_REPORTS/junit/


